world dashbook-parser {
  default export interface {

    record cell {
      cell-type: cell-type,
      size: s32,
      source: string,
      outputs: list<string>
    }

    variant cell-type {
      markdown,
      code,
      query
    }

    parse: func(input: string) -> list<cell>
    generate: func(cells: list<cell>) -> string
  }
}