package dashbook:dashbook-parser;

world dashbook-parser {
  export dashbook-parser: interface {
      
    variant error {
      parse-error
    }

    record cell {
      cell-type: cell-type,
      size: s32,
      source: string,
      outputs: list<cell-output>
    }

    variant cell-type {
      markdown,
      code,
      query
    }

    variant cell-output {
      text(string),
      html(string)
    }

    parse: func(input: string) -> result<list<cell>,error>;
    generate: func(cells: list<cell>) -> string;
  }
}
